# Generated by Django 4.2.5 on 2023-09-25 17:39

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('head', models.CharField(max_length=255, verbose_name='Haqqımızda başlıq hissəsi')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıqlama')),
                ('years_of_experience', models.CharField(max_length=255, verbose_name='Təcrübə')),
                ('count_of_workers', models.CharField(max_length=255, verbose_name='İşçilərin sayı')),
                ('img_1', models.ImageField(help_text='298x298', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Sol üst şəkil')),
                ('img_2', models.ImageField(help_text='224x224', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Sağ üst şəkil')),
                ('img_3', models.ImageField(help_text='224x224', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Sol aşağı şəkil')),
                ('img_4', models.ImageField(help_text='298x298', upload_to=services.uploader.Uploader.upload_photo_for_about, verbose_name='Sağ aşağı şəkil')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
                'ordering': ('-created_at',),
            },
        ),
    ]
