# Generated by Django 4.2.5 on 2023-09-26 16:53

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Xidmətin adı')),
                ('description', models.TextField(verbose_name='Xidmət haqqında')),
                ('icon', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_icon)),
            ],
            options={
                'verbose_name': 'Xidmət',
                'verbose_name_plural': 'Xidmətlər',
                'ordering': ('-created_at',),
            },
        ),
    ]
