# Generated by Django 4.2.5 on 2023-09-26 17:15

from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('image', models.ImageField(help_text='80x80', upload_to=services.uploader.Uploader.upload_photo_for_menu, verbose_name='Yeməyin şəkili')),
                ('food_name', models.CharField(max_length=255, verbose_name='Yeməyin adı')),
                ('receipt', models.CharField(max_length=255, verbose_name='Yeməyin tərkibi')),
                ('price', models.CharField(max_length=255, verbose_name='Yeməyin qiyməti')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.category')),
            ],
            options={
                'verbose_name': 'Menyu',
                'verbose_name_plural': 'Menyu',
                'ordering': ('-created_at',),
            },
        ),
    ]
