# Generated by Django 4.2.5 on 2023-10-02 16:52

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('main_text', models.TextField(verbose_name='Əsas cümlə')),
                ('sub_text', models.TextField(verbose_name='Alt mətin')),
                ('back_image', models.ImageField(help_text='1366x768', upload_to=services.uploader.Uploader.upload_photo_for_home_header, verbose_name='Arxa plan foto')),
                ('round_image', models.ImageField(help_text='612x612', upload_to=services.uploader.Uploader.upload_photo_for_home_header, verbose_name='Fırlanan foto')),
            ],
            options={
                'verbose_name': 'Ana səhifə başlıq',
                'verbose_name_plural': 'Ana səhifə başlıq',
                'ordering': ('-created_at',),
            },
        ),
    ]
