# Generated by Django 4.2.5 on 2023-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_homeheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('phone_number', models.CharField(max_length=255, verbose_name='Əlaqə nömrəsi')),
            ],
            options={
                'verbose_name': 'Abunə olan şəxs',
                'verbose_name_plural': 'Abunə olan şəxslər',
                'ordering': ('-created_at',),
            },
        ),
    ]
