# Generated by Django 4.2.5 on 2023-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Əlaqə nömrəsi'),
        ),
    ]
