# Generated by Django 4.2.5 on 2023-10-03 16:28

import ckeditor.fields
from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_alter_subscribe_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('location', models.TextField(verbose_name='Ünvan')),
                ('phone_number', models.TextField(verbose_name='Əlaqə nömrəsi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('working_time', ckeditor.fields.RichTextField(verbose_name='İş vaxtları')),
                ('logo', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_for_logo, verbose_name='Saytın loqosu')),
            ],
            options={
                'verbose_name': 'Əsas məlumat',
                'verbose_name_plural': 'Əsas məlumatlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
