# Generated by Django 4.2.5 on 2023-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_maindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindetails',
            name='working_time',
            field=models.TextField(verbose_name='İş vaxtları'),
        ),
    ]
