# Generated by Django 4.2.5 on 2023-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_maindetails_working_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('social_media', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('yt', 'Youtube'), ('tiktok', 'Tiktok'), ('telegram', 'Telegram'), ('linkedin', 'linkedin')], max_length=255, verbose_name='Sosial media')),
                ('link', models.TextField(verbose_name='Sosial media linki')),
            ],
            options={
                'verbose_name': 'Sosial media hesab',
                'verbose_name_plural': 'Sosial media hesabları',
                'ordering': ('-created_at',),
            },
        ),
    ]
