# Generated by Django 4.2.5 on 2023-10-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindetails',
            name='video_url',
            field=models.TextField(blank=True, null=True, verbose_name='Video linki'),
        ),
    ]
