# Generated by Django 3.2 on 2023-10-04 16:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_category_icon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_link',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Ikon'),
        ),
    ]
