# Generated by Django 3.2 on 2023-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_alter_category_icon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ikon'),
        ),
    ]
