# Generated by Django 4.2.5 on 2023-10-09 17:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_remove_category_icon_link_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_et',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıqlama'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='head_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Haqqımızda başlıq hissəsi'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='head_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Haqqımızda başlıq hissəsi'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='head_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Haqqımızda başlıq hissəsi'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriyalar'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriyalar'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriyalar'),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='main_text_en',
            field=models.TextField(null=True, verbose_name='Əsas cümlə'),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='main_text_et',
            field=models.TextField(null=True, verbose_name='Əsas cümlə'),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='main_text_ru',
            field=models.TextField(null=True, verbose_name='Əsas cümlə'),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='sub_text_en',
            field=models.TextField(null=True, verbose_name='Alt mətin'),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='sub_text_et',
            field=models.TextField(null=True, verbose_name='Alt mətin'),
        ),
        migrations.AddField(
            model_name='homeheader',
            name='sub_text_ru',
            field=models.TextField(null=True, verbose_name='Alt mətin'),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='location_en',
            field=models.TextField(null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='location_et',
            field=models.TextField(null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='location_ru',
            field=models.TextField(null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='working_time_en',
            field=models.TextField(null=True, verbose_name='İş vaxtları'),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='working_time_et',
            field=models.TextField(null=True, verbose_name='İş vaxtları'),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='working_time_ru',
            field=models.TextField(null=True, verbose_name='İş vaxtları'),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Yeməyin adı'),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Yeməyin adı'),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Yeməyin adı'),
        ),
        migrations.AddField(
            model_name='menu',
            name='receipt_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Yeməyin tərkibi'),
        ),
        migrations.AddField(
            model_name='menu',
            name='receipt_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Yeməyin tərkibi'),
        ),
        migrations.AddField(
            model_name='menu',
            name='receipt_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Yeməyin tərkibi'),
        ),
        migrations.AddField(
            model_name='personal',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='İşçinin vəzifəsi'),
        ),
        migrations.AddField(
            model_name='personal',
            name='position_et',
            field=models.CharField(max_length=255, null=True, verbose_name='İşçinin vəzifəsi'),
        ),
        migrations.AddField(
            model_name='personal',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='İşçinin vəzifəsi'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Xidmət haqqında'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_et',
            field=models.TextField(null=True, verbose_name='Xidmət haqqında'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Xidmət haqqında'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Xidmətin adı'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Xidmətin adı'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Xidmətin adı'),
        ),
    ]
