# Generated by Django 4.2.5 on 2024-01-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_maindetails_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringMenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Catering Menyu kateqoriya',
                'verbose_name_plural': 'Catering Menyu kateqoriyaları',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CateringMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Yemək adı')),
                ('ingredients', models.TextField(verbose_name='Tərkibi')),
                ('price', models.FloatField(verbose_name='Qiymət')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.cateringmenucategories')),
            ],
            options={
                'verbose_name': 'Catering menu',
                'verbose_name_plural': 'Catering menu',
                'ordering': ('-created_at',),
            },
        ),
    ]
