# Generated by Django 4.2.5 on 2024-01-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_cateringmenucategories_cateringmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringmenu',
            name='ingredients_en',
            field=models.TextField(null=True, verbose_name='Tərkibi'),
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='ingredients_et',
            field=models.TextField(null=True, verbose_name='Tərkibi'),
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='ingredients_ru',
            field=models.TextField(null=True, verbose_name='Tərkibi'),
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Yemək adı'),
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Yemək adı'),
        ),
        migrations.AddField(
            model_name='cateringmenu',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Yemək adı'),
        ),
        migrations.AddField(
            model_name='cateringmenucategories',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='cateringmenucategories',
            name='name_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriya'),
        ),
        migrations.AddField(
            model_name='cateringmenucategories',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Kateqoriya'),
        ),
    ]
