# Generated by Django 4.2.5 on 2024-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_cateringmenu_ingredients_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindetails',
            name='catering_menu_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
