# Generated by Django 4.2.5 on 2024-01-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_maindetails_catering_menu_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindetails',
            name='catering_menu_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='catering_menu_text_et',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maindetails',
            name='catering_menu_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
