# Generated by Django 4.2.5 on 2024-01-08 20:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_cateringmenu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindetails',
            name='working_time',
            field=ckeditor.fields.RichTextField(verbose_name='İş vaxtları'),
        ),
        migrations.AlterField(
            model_name='maindetails',
            name='working_time_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İş vaxtları'),
        ),
        migrations.AlterField(
            model_name='maindetails',
            name='working_time_et',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İş vaxtları'),
        ),
        migrations.AlterField(
            model_name='maindetails',
            name='working_time_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='İş vaxtları'),
        ),
    ]
