# Generated by Django 4.2.5 on 2024-02-14 17:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0027_alter_maindetails_working_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindetails',
            name='catering_menu_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maindetails',
            name='catering_menu_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maindetails',
            name='catering_menu_text_et',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maindetails',
            name='catering_menu_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
