# Generated by Django 4.2.5 on 2024-03-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0028_alter_maindetails_catering_menu_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindetails',
            name='contact_text',
            field=models.TextField(blank=True, null=True, verbose_name='Contact hissesi aciqlama'),
        ),
    ]
